### ISSUE TITLE
plex_theme_songs.py - AttributeError: module 'urllib' has no attribute 'urlretrieve'

### ISSUE THREAD

**Issue by UnR34L** [blacktwin/JBOPS#89]
Installed plexapi, ran

> python3.6 ./plex_theme_songs.py

Got this

>Traceback (most recent call last):
>File "./plex_theme_songs.py", line 39, in <module>
>urllib.urlretrieve(themes_url.format(tvdb_id), theme_path)
>AttributeError: module 'urllib' has no attribute 'urlretrieve'

**Comment by blacktwin** [comment]
This has only been tested in python 2.7.

**Comment by UnR34L** [comment]
Worked with python2.7
